CREATE TABLE [stg].[FacturaDetalle] (
    [DocEntry]         INT             NULL,
    [LineNum]          INT             NULL,
    [ItemCode]         VARCHAR (500)   NULL,
    [Price]            DECIMAL (18, 2) NULL,
    [Currency]         VARCHAR (20)    NULL,
    [LineTotal]        DECIMAL (18, 2) NULL,
    [OpenSum]          DECIMAL (18, 2) NULL,
    [SlpCode]          INT             NULL,
    [AcctCode]         VARCHAR (500)   NULL,
    [PriceBefDi]       DECIMAL (18, 2) NULL,
    [DocDate]          DATETIME        NULL,
    [BaseCard]         VARCHAR (500)   NULL,
    [TotalSumSy]       DECIMAL (18, 2) NULL,
    [OpenSumSys]       DECIMAL (18, 2) NULL,
    [VatPrcnt]         DECIMAL (18, 2) NULL,
    [PriceAfVAT]       DECIMAL (18, 2) NULL,
    [VatSum]           DECIMAL (18, 2) NULL,
    [VatSumSy]         DECIMAL (18, 2) NULL,
    [DedVatSum]        DECIMAL (18, 2) NULL,
    [DedVatSumS]       DECIMAL (18, 2) NULL,
    [GrssProfit]       DECIMAL (18, 2) NULL,
    [GrssProfSC]       DECIMAL (18, 2) NULL,
    [VisOrder]         INT             NULL,
    [INMPrice]         DECIMAL (18, 2) NULL,
    [TaxCode]          VARCHAR (100)   NULL,
    [LineVat]          DECIMAL (18, 2) NULL,
    [LineVatS]         DECIMAL (18, 2) NULL,
    [OwnerCode]        VARCHAR (500)   NULL,
    [StockSum]         DECIMAL (18, 2) NULL,
    [StockSumSc]       DECIMAL (18, 2) NULL,
    [ShipToCode]       VARCHAR (500)   NULL,
    [ShipToDesc]       VARCHAR (500)   NULL,
    [GTotal]           DECIMAL (18, 2) NULL,
    [GTotalSC]         DECIMAL (18, 2) NULL,
    [TaxOnly]          VARCHAR (500)   NULL,
    [CogsOcrCod]       INT             NULL,
    [CogsAcct]         VARCHAR (500)   NULL,
    [CogsOcrCo2]       INT             NULL,
    [CogsOcrCo3]       INT             NULL,
    [CogsOcrCo4]       INT             NULL,
    [CogsOcrCo5]       INT             NULL,
    [GPBefDisc]        DECIMAL (18, 2) NULL,
    [WtLiable]         VARCHAR (1)     NULL,
    [GrssProfFC]       DECIMAL (18, 2) NULL,
    [LicTradNum]       VARCHAR (32)    NULL,
    [FreeTxt]          VARCHAR (100)   NULL,
    [NatOfTrans]       INT             NULL,
    [PostTax]          VARCHAR (1)     NULL,
    [LstByDsSum]       DECIMAL (18, 2) NULL,
    [MYFtype]          VARCHAR (2)     NULL,
    [PartRetire]       VARCHAR (1)     NULL,
    [U_RBI_CantOriOc]  DECIMAL (18, 2) NULL,
    [LocCode]          INT             NULL,
    [StckAppSc]        DECIMAL (18, 2) NULL,
    [BlockNum]         VARCHAR (100)   NULL,
    [VatExEntry]       INT             NULL,
    [StckAppDFC]       DECIMAL (18, 2) NULL,
    [SacEntry]         INT             NULL,
    [CFOPCode]         VARCHAR (6)     NULL,
    [OrderedQty]       VARCHAR (300)   NULL,
    [Address]          VARCHAR (254)   NULL,
    [PrntLnNum]        INT             NULL,
    [RG23APart1]       INT             NULL,
    [DstrbSumSC]       DECIMAL (18, 2) NULL,
    [EnSetCost]        VARCHAR (1)     NULL,
    [LineVendor]       VARCHAR (15)    NULL,
    [Wght2Unit]        INT             NULL,
    [RetirAPCFC]       DECIMAL (18, 2) NULL,
    [BaseAtCard]       VARCHAR (100)   NULL,
    [DiscPrcnt]        DECIMAL (18, 2) NULL,
    [ReturnAct]        INT             NULL,
    [LegalTTCA]        VARCHAR (250)   NULL,
    [ShipFromDe]       VARCHAR (254)   NULL,
    [Shortages]        DECIMAL (18, 2) NULL,
    [TaxDistSFC]       DECIMAL (18, 2) NULL,
    [PackQty]          DECIMAL (18, 2) NULL,
    [EquVatPer]        DECIMAL (18, 2) NULL,
    [DistribIS]        VARCHAR (1)     NULL,
    [StckAppFc]        DECIMAL (18, 2) NULL,
    [LogInstanc]       INT             NULL,
    [LinePoPrss]       VARCHAR (1)     NULL,
    [EquVatSumF]       DECIMAL (18, 2) NULL,
    [U_CodComer]       VARCHAR (10)    NULL,
    [ActBaseEnt]       INT             NULL,
    [ExpType]          VARCHAR (4)     NULL,
    [PoTrgNum]         INT             NULL,
    [AgrLnNum]         INT             NULL,
    [NumPerMsr]        DECIMAL (18, 2) NULL,
    [LegalTW]          VARCHAR (250)   NULL,
    [LineStatus]       VARCHAR (1)     NULL,
    [NVECode]          VARCHAR (6)     NULL,
    [GrossBuyPr]       DECIMAL (18, 2) NULL,
    [EquVatSumS]       DECIMAL (18, 2) NULL,
    [StckSumApp]       DECIMAL (18, 2) NULL,
    [OrigItem]         VARCHAR (50)    NULL,
    [BaseDocNum]       INT             NULL,
    [RG23APart2]       INT             NULL,
    [PcDocType]        INT             NULL,
    [AgrNo]            INT             NULL,
    [Dscription]       VARCHAR (200)   NULL,
    [CSTfIPI]          VARCHAR (2)     NULL,
    [ItemType]         INT             NULL,
    [FinncPriod]       INT             NULL,
    [DefBreak]         DECIMAL (18, 2) NULL,
    [LnExcised]        VARCHAR (1)     NULL,
    [TargetType]       INT             NULL,
    [StckAppD]         DECIMAL (18, 2) NULL,
    [StockSumFc]       DECIMAL (18, 2) NULL,
    [OcrCode]          VARCHAR (8)     NULL,
    [PoNum]            VARCHAR (20)    NULL,
    [Len1Unit]         INT             NULL,
    [LegalText]        VARCHAR (254)   NULL,
    [Surpluses]        DECIMAL (18, 2) NULL,
    [SWW]              VARCHAR (16)    NULL,
    [LstByDsSc]        DECIMAL (18, 2) NULL,
    [LineType]         VARCHAR (1)     NULL,
    [GPTtlBasPr]       DECIMAL (18, 2) NULL,
    [TaxDistSum]       DECIMAL (18, 2) NULL,
    [DropShip]         VARCHAR (1)     NULL,
    [QtyToShip]        DECIMAL (18, 2) NULL,
    [TaxRelev]         VARCHAR (1)     NULL,
    [TaxType]          VARCHAR (1)     NULL,
    [VatWoDpm]         DECIMAL (18, 2) NULL,
    [ToStock]          DECIMAL (18, 2) NULL,
    [TotInclTax]       DECIMAL (18, 2) NULL,
    [InvntSttus]       VARCHAR (1)     NULL,
    [TreeType]         VARCHAR (1)     NULL,
    [TrnsCode]         INT             NULL,
    [DetailsOW]        VARCHAR (1)     NULL,
    [U_CodFide]        VARCHAR (10)    NULL,
    [U_DesLin]         DECIMAL (18, 2) NULL,
    [LstByDsFc]        DECIMAL (18, 2) NULL,
    [U_RBI_CantConf]   DECIMAL (18, 2) NULL,
    [PickOty]          DECIMAL (18, 2) NULL,
    [RG23CPart1]       INT             NULL,
    [RG23CPart2]       INT             NULL,
    [ISDistrb]         DECIMAL (18, 2) NULL,
    [UnencReasn]       INT             NULL,
    [UomCode2]         VARCHAR (20)    NULL,
    [InvQty]           DECIMAL (18, 2) NULL,
    [UomEntry]         INT             NULL,
    [BaseEntry]        INT             NULL,
    [DistribExp]       VARCHAR (1)     NULL,
    [UomEntry2]        INT             NULL,
    [Usage]            INT             NULL,
    [UseBaseUn]        VARCHAR (1)     NULL,
    [VatAppld]         DECIMAL (18, 2) NULL,
    [VatAppldSC]       DECIMAL (18, 2) NULL,
    [VatGroup]         VARCHAR (8)     NULL,
    [Excisable]        VARCHAR (1)     NULL,
    [VatGrpSrc]        VARCHAR (1)     NULL,
    [CSTCode]          VARCHAR (6)     NULL,
    [ToDiff]           DECIMAL (18, 2) NULL,
    [UpdInvntry]       VARCHAR (1)     NULL,
    [ActBaseNum]       INT             NULL,
    [VatWoDpmFc]       DECIMAL (18, 2) NULL,
    [StckDstSum]       DECIMAL (18, 2) NULL,
    [VendorNum]        VARCHAR (50)    NULL,
    [Wdth1Unit]        INT             NULL,
    [Wdth2Unit]        INT             NULL,
    [ISDistrbFC]       DECIMAL (18, 2) NULL,
    [Len2Unit]         INT             NULL,
    [RetCost]          DECIMAL (18, 2) NULL,
    [WhsCode]          VARCHAR (8)     NULL,
    [Flags]            INT             NULL,
    [UFFiscBene]       VARCHAR (10)    NULL,
    [Width1]           DECIMAL (18, 2) NULL,
    [IsAqcuistn]       VARCHAR (1)     NULL,
    [Hght1Unit]        INT             NULL,
    [isSrvCall]        VARCHAR (1)     NULL,
    [PickStatus]       VARCHAR (1)     NULL,
    [unitMsr]          VARCHAR (100)   NULL,
    [IndEscala]        VARCHAR (1)     NULL,
    [EquVatSum]        DECIMAL (18, 2) NULL,
    [VatDscntPr]       DECIMAL (18, 2) NULL,
    [OpenInvQty]       DECIMAL (18, 2) NULL,
    [CSTfPIS]          VARCHAR (2)     NULL,
    [unitMsr2]         VARCHAR (100)   NULL,
    [CodeBars]         VARCHAR (254)   NULL,
    [StockValue]       DECIMAL (18, 2) NULL,
    [VatAppldFC]       DECIMAL (18, 2) NULL,
    [AssblValue]       DECIMAL (18, 2) NULL,
    [DeferrTax]        VARCHAR (1)     NULL,
    [BaseRef]          VARCHAR (16)    NULL,
    [ItmTaxType]       VARCHAR (2)     NULL,
    [PQTReqDate]       DATETIME        NULL,
    [PQTReqQty]        DECIMAL (18, 2) NULL,
    [ISDtCryImp]       VARCHAR (3)     NULL,
    [CredOrigin]       VARCHAR (1)     NULL,
    [NCMCode]          INT             NULL,
    [length2]          DECIMAL (18, 2) NULL,
    [ReturnRsn]        INT             NULL,
    [StckAppDSC]       DECIMAL (18, 2) NULL,
    [DelivrdQty]       DECIMAL (18, 2) NULL,
    [HsnEntry]         INT             NULL,
    [CESTCode]         INT             NULL,
    [GTotalFC]         DECIMAL (18, 2) NULL,
    [OriBAbsEnt]       INT             NULL,
    [RetirAPCSC]       DECIMAL (18, 2) NULL,
    [LinManClsd]       VARCHAR (1)     NULL,
    [TaxPerUnit]       DECIMAL (18, 2) NULL,
    [Hght2Unit]        INT             NULL,
    [OriBDocTyp]       INT             NULL,
    [NoInvtryMv]       VARCHAR (1)     NULL,
    [Commission]       DECIMAL (18, 2) NULL,
    [TaxDistSSC]       DECIMAL (18, 2) NULL,
    [ExpUUID]          VARCHAR (50)    NULL,
    [U_RBI_Comprador]  VARCHAR (30)    NULL,
    [RetireAPC]        DECIMAL (18, 2) NULL,
    [BaseQty]          DECIMAL (18, 2) NULL,
    [FisrtBin]         VARCHAR (228)   NULL,
    [PoItmNum]         INT             NULL,
    [DIOTNat]          VARCHAR (3)     NULL,
    [StgEntry]         INT             NULL,
    [ShipFromCo]       VARCHAR (50)    NULL,
    [StckDstFc]        DECIMAL (18, 2) NULL,
    [CUSplit]          VARCHAR (1)     NULL,
    [NumPerMsr2]       DECIMAL (18, 2) NULL,
    [Project]          VARCHAR (20)    NULL,
    [NeedQty]          VARCHAR (1)     NULL,
    [PcQuantity]       DECIMAL (18, 2) NULL,
    [UomCode]          VARCHAR (20)    NULL,
    [ISDtRgnImp]       INT             NULL,
    [VatSumFrgn]       DECIMAL (18, 2) NULL,
    [ShipDate]         DATETIME        NULL,
    [SubCatNum]        VARCHAR (50)    NULL,
    [RevCharge]        VARCHAR (1)     NULL,
    [DedVatSumF]       DECIMAL (18, 2) NULL,
    [Rate]             DECIMAL (18, 2) NULL,
    [EncryptIV]        VARCHAR (100)   NULL,
    [Width2]           DECIMAL (18, 2) NULL,
    [ExLineNo]         VARCHAR (10)    NULL,
    [FreeChrgBP]       VARCHAR (1)     NULL,
    [GrossBase]        INT             NULL,
    [CSTfCOFINS]       VARCHAR (2)     NULL,
    [OpenRtnQty]       DECIMAL (18, 2) NULL,
    [ThirdParty]       VARCHAR (1)     NULL,
    [ConsumeFCT]       VARCHAR (1)     NULL,
    [OpenQty]          DECIMAL (18, 2) NULL,
    [StockPrice]       DECIMAL (18, 2) NULL,
    [StdItemId]        INT             NULL,
    [TotalFrgn]        DECIMAL (18, 2) NULL,
    [StgDesc]          VARCHAR (100)   NULL,
    [ISDistrbSC]       DECIMAL (18, 2) NULL,
    [SerialNum]        VARCHAR (17)    NULL,
    [ExciseAmt]        DECIMAL (21)    NULL,
    [IsByPrdct]        VARCHAR (1)     NULL,
    [CNJPMan]          VARCHAR (14)    NULL,
    [ActBaseLn]        INT             NULL,
    [TaxAmtSrc]        VARCHAR (1)     NULL,
    [WtCalced]         VARCHAR (1)     NULL,
    [IsCstmAct]        VARCHAR (1)     NULL,
    [StckINMPr]        DECIMAL (18, 2) NULL,
    [OpenCreQty]       DECIMAL (18, 2) NULL,
    [PickIdNo]         INT             NULL,
    [SpecPrice]        VARCHAR (1)     NULL,
    [ExtTaxSumF]       DECIMAL (18, 2) NULL,
    [BasePrice]        VARCHAR (1)     NULL,
    [ObjType]          VARCHAR (20)    NULL,
    [U_CodLin]         VARCHAR (10)    NULL,
    [LstBINMPr]        DECIMAL (18, 2) NULL,
    [TaxStatus]        VARCHAR (1)     NULL,
    [LegalTIMD]        VARCHAR (250)   NULL,
    [ExtTaxSumS]       DECIMAL (18, 2) NULL,
    [TrgetEntry]       INT             NULL,
    [Weight1]          DECIMAL (18, 2) NULL,
    [Weight2]          DECIMAL (18, 2) NULL,
    [CiOppLineN]       INT             NULL,
    [InvQtyOnly]       VARCHAR (1)     NULL,
    [DstrbSumFC]       DECIMAL (18, 2) NULL,
    [ExpOpType]        VARCHAR (1)     NULL,
    [BaseOpnQty]       DECIMAL (18, 2) NULL,
    [Length1]          DECIMAL (18, 2) NULL,
    [BaseType]         INT             NULL,
    [OriBLinNum]       INT             NULL,
    [RetireQty]        DECIMAL (18, 2) NULL,
    [VatExLN]          INT             NULL,
    [ISOrCryExp]       VARCHAR (3)     NULL,
    [StckDstSc]        DECIMAL (18, 2) NULL,
    [CountryOrg]       VARCHAR (3)     NULL,
    [DistribSum]       DECIMAL (18, 2) NULL,
    [VolUnit]          INT             NULL,
    [Height1]          DECIMAL (18, 2) NULL,
    [Height2]          DECIMAL (18, 2) NULL,
    [LineVatlF]        DECIMAL (18, 2) NULL,
    [TranType]         VARCHAR (1)     NULL,
    [PoTrgEntry]       VARCHAR (11)    NULL,
    [PoLineNum]        INT             NULL,
    [AllocBinC]        VARCHAR (11)    NULL,
    [Volume]           DECIMAL (18, 2) NULL,
    [ReleasQtty]       DECIMAL (18, 2) NULL,
    [CtrSealQty]       DECIMAL (18, 2) NULL,
    [Factor1]          DECIMAL (18, 2) NULL,
    [Factor2]          DECIMAL (18, 2) NULL,
    [Factor3]          DECIMAL (18, 2) NULL,
    [Factor4]          DECIMAL (18, 2) NULL,
    [BaseLine]         INT             NULL,
    [StgSeqNum]        INT             NULL,
    [U_DescCComer]     DECIMAL (18, 2) NULL,
    [ImportLog]        VARCHAR (20)    NULL,
    [ISOrRgnExp]       INT             NULL,
    [PriceEdit]        VARCHAR (1)     NULL,
    [FromWhsCod]       VARCHAR (8)     NULL,
    [OcrCode2]         VARCHAR (8)     NULL,
    [OcrCode3]         VARCHAR (8)     NULL,
    [OcrCode4]         VARCHAR (8)     NULL,
    [OcrCode5]         VARCHAR (8)     NULL,
    [LegalTCD]         VARCHAR (250)   NULL,
    [U_RBI_DispVentas] DECIMAL (18, 2) NULL,
    [ExtTaxSum]        DECIMAL (18, 2) NULL,
    [ExtTaxRate]       DECIMAL (18, 2) NULL,
    [OpenSumFC]        DECIMAL (18, 2) NULL,
    [Wght1Unit]        INT             NULL,
    [VatWoDpmSc]       DECIMAL (18, 2) NULL,
    [BackOrdr]         VARCHAR (1)     NULL,
    [U_DescFide]       DECIMAL (18, 2) NULL,
    [IsPrscGood]       VARCHAR (1)     NULL,
    [DescOW]           VARCHAR (1)     NULL,
    [Incoterms]        INT             NULL,
    [CommClass]        INT             NULL,
    [CEECFlag]         VARCHAR (1)     NULL,
    [ActDelDate]       DATETIME        NULL,
    [TransMod]         INT             NULL,
    [ChgAsmBoMW]       VARCHAR (1)     NULL
);


go

CREATE NONCLUSTERED INDEX [ind_factura_Detalle]
ON [stg].[FacturaDetalle] ([DocEntry])
INCLUDE ([LineNum],[ItemCode],[Price],[Currency],[LineTotal],[OpenSum],[SlpCode],[AcctCode],[PriceBefDi],[DocDate],[BaseCard],[TotalSumSy],[OpenSumSys],[VatPrcnt],[PriceAfVAT],[VatSum],[VatSumSy],[DedVatSum],[DedVatSumS],[GrssProfit],[GrssProfSC],[VisOrder],[INMPrice],[TaxCode],[LineVat],[LineVatS],[OwnerCode],[StockSum],[StockSumSc],[ShipToCode],[ShipToDesc],[GTotal],[GTotalSC],[TaxOnly],[CogsOcrCod],[CogsAcct],[CogsOcrCo2],[CogsOcrCo3],[CogsOcrCo4],[CogsOcrCo5],[GPBefDisc])
GO
