CREATE TABLE [stg].[Inventario]
(
TransNum varchar(max),
TransType varchar(max),
CreatedBy varchar(max),
BASE_REF varchar(max),
DocLineNum varchar(max),
DocDate varchar(max),
DocDueDate varchar(max),
CardCode varchar(max),
CardName varchar(max),
Ref1 varchar(max),
Ref2 varchar(max),
Comments varchar(max),
JrnlMemo varchar(max),
DocTime varchar(max),
ItemCode varchar(max),
Dscription varchar(max),
InQty decimal (18,4),
OutQty decimal (18,4),
Price decimal (18,4),
Currency varchar(max),
Rate decimal (18,4),
VendorNum varchar(max),
SerialNum varchar(max),
Warehouse varchar(max),
TreeType varchar(max),
SlpCode varchar(max),
TaxDate varchar(max),
DataSource varchar(max),
PrjCode varchar(max),
UserSign varchar(max),
BlockNum varchar(max),
ImportLog varchar(max),
UseDocPric varchar(max),
[Location] varchar(max),
CalcPrice decimal (18,4),
OpenQty decimal (18,4),
Instance varchar(max),
LastInst varchar(max),
RevalTotal decimal (18,4),
BaseCurr varchar(max),
ApplObj varchar(max),
AppObjAbs varchar(max),
AppObjType varchar(max),
StockAct varchar(max),
TrnsfrAct varchar(max),
PriceDifAc varchar(max),
VarianceAc varchar(max),
ReturnAct varchar(max),
ExcRateAct varchar(max),
ClearAct varchar(max),
CostAct varchar(max),
WipAct varchar(max),
Balance decimal (18,4),
CreateDate  varchar(max),
BaseLine varchar(max),
TransValue decimal (18,4),
PriceDiff decimal (18,4),
TransSeq varchar(max),
InvntAct varchar(max),
RemMethod varchar(max),
OpenValue decimal (18,4),
SubLineNum varchar(max),
AppObjLine varchar(max),
Expenses decimal (18,4),
OpenExp decimal (18,4),
Allocation decimal (18,4),
OpenAlloc decimal (18,4),
ExpAlloc decimal (18,4),
OExpAlloc decimal (18,4),
OpenPDiff decimal (18,4),
ExchDiff decimal (18,4),
OpenEDiff decimal (18,4),
NegInvAdjs decimal (18,4),
OpenNegInv decimal (18,4),
NegStckAct varchar(max),
BTransVal varchar(max),
VarVal decimal (18,4),
BExpVal decimal (18,4),
CogsVal decimal (18,4),
BNegAVal decimal (18,4),
IOffIncAcc varchar(max),
IOffIncVal decimal (18,4),
DOffDecAcc varchar(max),
DOffDecVal decimal (18,4),
DecAcc varchar(max),
DecVal decimal (18,4),
WipVal decimal (18,4),
WipVarAcc varchar(max),
WipVarVal decimal (18,4),
IncAct varchar(max),
IncVal decimal (18,4),
ExpCAcc varchar(max),
CostMethod varchar(max),
OcrCode varchar(max),
BaseQty varchar(max),
PrevTrans varchar(max),
HTransSeq varchar(max),
OcrCode2 varchar(max),
OcrCode3 varchar(max),
OcrCode4 varchar(max),
OcrCode5 varchar(max),
StgSeqNum varchar(max),
StgEntry varchar(max),
StgDesc varchar(max)


)
