CREATE TABLE [stg].[OrdenCompraDetalle] (
	[DocEntry] [int] NULL,
	[LineNum] [int] NULL,
	[ItemCode] [varchar](500) NULL,
	[Price] [decimal](18, 2) NULL,
	[Currency] [varchar](20) NULL,
	[LineTotal] [decimal](18, 2) NULL,
	[OpenSum] [decimal](18, 2) NULL,
	[SlpCode] [int] NULL,
	[AcctCode] [varchar](500) NULL,
	[PriceBefDi] [decimal](18, 2) NULL,
	[DocDate] [datetime] NULL,
	[BaseCard] [varchar](500) NULL,
	[TotalSumSy] [decimal](18, 2) NULL,
	[OpenSumSys] [decimal](18, 2) NULL,
	[VatPrcnt] [decimal](18, 2) NULL,
	[PriceAfVAT] [decimal](18, 2) NULL,
	[VatSum] [decimal](18, 2) NULL,
	[VatSumSy] [decimal](18, 2) NULL,
	[DedVatSum] [decimal](18, 2) NULL,
	[DedVatSumS] [decimal](18, 2) NULL,
	[GrssProfit] [decimal](18, 2) NULL,
	[GrssProfSC] [decimal](18, 2) NULL,
	[VisOrder] [int] NULL,
	[INMPrice] [decimal](18, 2) NULL,
	[TaxCode] [varchar](100) NULL,
	[LineVat] [decimal](18, 2) NULL,
	[LineVatS] [decimal](18, 2) NULL,
	[OwnerCode] [varchar](500) NULL,
	[StockSum] [decimal](18, 2) NULL,
	[StockSumSc] [decimal](18, 2) NULL,
	[ShipToCode] [varchar](500) NULL,
	[ShipToDesc] [varchar](500) NULL,
	[GTotal] [decimal](18, 2) NULL,
	[GTotalSC] [decimal](18, 2) NULL,
	[TaxOnly] [varchar](500) NULL,
	[CogsOcrCod] [int] NULL,
	[CogsAcct] [varchar](500) NULL,
	[CogsOcrCo2] [int] NULL,
	[CogsOcrCo3] [int] NULL,
	[CogsOcrCo4] [int] NULL,
	[CogsOcrCo5] [int] NULL,
	[GPBefDisc] [decimal](18, 2) NULL,
	[WtLiable] [varchar](1) NULL,
	[GrssProfFC] [decimal](18, 2) NULL,
	[LicTradNum] [varchar](32) NULL,
	[FreeTxt] [varchar](100) NULL,
	[NatOfTrans] [int] NULL,
	[PostTax] [varchar](1) NULL,
	[LstByDsSum] [decimal](18, 2) NULL,
	[MYFtype] [varchar](2) NULL,
	[PartRetire] [varchar](1) NULL,
	[U_RBI_CantOriOc] [decimal](18, 2) NULL,
	[LocCode] [int] NULL,
	[StckAppSc] [decimal](18, 2) NULL,
	[BlockNum] [varchar](100) NULL,
	[VatExEntry] [int] NULL,
	[StckAppDFC] [decimal](18, 2) NULL,
	[SacEntry] [int] NULL,
	[CFOPCode] [varchar](6) NULL,
	[OrderedQty] [varchar](300) NULL,
	[Address] [varchar](254) NULL,
	[PrntLnNum] [int] NULL,
	[RG23APart1] [int] NULL,
	[DstrbSumSC] [decimal](18, 2) NULL,
	[EnSetCost] [varchar](1) NULL,
	[LineVendor] [varchar](15) NULL,
	[Wght2Unit] [int] NULL,
	[RetirAPCFC] [decimal](18, 2) NULL,
	[BaseAtCard] [varchar](100) NULL,
	[DiscPrcnt] [decimal](18, 2) NULL,
	[ReturnAct] [int] NULL,
	[LegalTTCA] [varchar](250) NULL,
	[ShipFromDe] [varchar](254) NULL,
	[Shortages] [decimal](18, 2) NULL,
	[TaxDistSFC] [decimal](18, 2) NULL,
	[PackQty] [decimal](18, 2) NULL,
	[EquVatPer] [decimal](18, 2) NULL,
	[DistribIS] [varchar](1) NULL,
	[StckAppFc] [decimal](18, 2) NULL,
	[LogInstanc] [int] NULL,
	[LinePoPrss] [varchar](1) NULL,
	[EquVatSumF] [decimal](18, 2) NULL,
	[U_CodComer] [varchar](10) NULL,
	[ActBaseEnt] [int] NULL,
	[ExpType] [varchar](4) NULL,
	[PoTrgNum] [int] NULL,
	[AgrLnNum] [int] NULL,
	[NumPerMsr] [decimal](18, 2) NULL,
	[LegalTW] [varchar](250) NULL,
	[LineStatus] [varchar](1) NULL,
	[NVECode] [varchar](6) NULL,
	[GrossBuyPr] [decimal](18, 2) NULL,
	[EquVatSumS] [decimal](18, 2) NULL,
	[StckSumApp] [decimal](18, 2) NULL,
	[OrigItem] [varchar](50) NULL,
	[BaseDocNum] [int] NULL,
	[RG23APart2] [int] NULL,
	[PcDocType] [int] NULL,
	[AgrNo] [int] NULL,
	[Dscription] [varchar](200) NULL,
	[CSTfIPI] [varchar](2) NULL,
	[ItemType] [int] NULL,
	[FinncPriod] [int] NULL,
	[DefBreak] [decimal](18, 2) NULL,
	[LnExcised] [varchar](1) NULL,
	[TargetType] [int] NULL,
	[StckAppD] [decimal](18, 2) NULL,
	[StockSumFc] [decimal](18, 2) NULL,
	[OcrCode] [varchar](8) NULL,
	[PoNum] [varchar](20) NULL,
	[Len1Unit] [int] NULL,
	[LegalText] [varchar](254) NULL,
	[Surpluses] [decimal](18, 2) NULL,
	[SWW] [varchar](16) NULL,
	[LstByDsSc] [decimal](18, 2) NULL,
	[LineType] [varchar](1) NULL,
	[GPTtlBasPr] [decimal](18, 2) NULL,
	[TaxDistSum] [decimal](18, 2) NULL,
	[DropShip] [varchar](1) NULL,
	[QtyToShip] [decimal](18, 2) NULL,
	[TaxRelev] [varchar](1) NULL,
	[TaxType] [varchar](1) NULL,
	[VatWoDpm] [decimal](18, 2) NULL,
	[ToStock] [decimal](18, 2) NULL,
	[TotInclTax] [decimal](18, 2) NULL,
	[InvntSttus] [varchar](1) NULL,
	[TreeType] [varchar](1) NULL,
	[TrnsCode] [int] NULL,
	[DetailsOW] [varchar](1) NULL,
	[U_CodFide] [varchar](10) NULL,
	[U_DesLin] [decimal](18, 2) NULL,
	[LstByDsFc] [decimal](18, 2) NULL,
	[U_RBI_CantConf] [decimal](18, 2) NULL,
	[PickOty] [decimal](18, 2) NULL,
	[RG23CPart1] [int] NULL,
	[RG23CPart2] [int] NULL,
	[ISDistrb] [decimal](18, 2) NULL,
	[UnencReasn] [int] NULL,
	[UomCode2] [varchar](20) NULL,
	[InvQty] [decimal](18, 2) NULL,
	[UomEntry] [int] NULL,
	[BaseEntry] [int] NULL,
	[DistribExp] [varchar](1) NULL,
	[UomEntry2] [int] NULL,
	[Usage] [int] NULL,
	[UseBaseUn] [varchar](1) NULL,
	[VatAppld] [decimal](18, 2) NULL,
	[VatAppldSC] [decimal](18, 2) NULL,
	[VatGroup] [varchar](8) NULL,
	[Excisable] [varchar](1) NULL,
	[VatGrpSrc] [varchar](1) NULL,
	[CSTCode] [varchar](6) NULL,
	[ToDiff] [decimal](18, 2) NULL,
	[UpdInvntry] [varchar](1) NULL,
	[ActBaseNum] [int] NULL,
	[VatWoDpmFc] [decimal](18, 2) NULL,
	[StckDstSum] [decimal](18, 2) NULL,
	[VendorNum] [varchar](50) NULL,
	[Wdth1Unit] [int] NULL,
	[Wdth2Unit] [int] NULL,
	[ISDistrbFC] [decimal](18, 2) NULL,
	[Len2Unit] [int] NULL,
	[RetCost] [decimal](18, 2) NULL,
	[WhsCode] [varchar](8) NULL,
	[Flags] [int] NULL,
	[UFFiscBene] [varchar](10) NULL,
	[Width1] [decimal](18, 2) NULL,
	[IsAqcuistn] [varchar](1) NULL,
	[Hght1Unit] [int] NULL,
	[isSrvCall] [varchar](1) NULL,
	[PickStatus] [varchar](1) NULL,
	[unitMsr] [varchar](100) NULL,
	[IndEscala] [varchar](1) NULL,
	[EquVatSum] [decimal](18, 2) NULL,
	[VatDscntPr] [decimal](18, 2) NULL,
	[OpenInvQty] [decimal](18, 2) NULL,
	[CSTfPIS] [varchar](2) NULL,
	[unitMsr2] [varchar](100) NULL,
	[CodeBars] [varchar](254) NULL,
	[StockValue] [decimal](18, 2) NULL,
	[VatAppldFC] [decimal](18, 2) NULL,
	[AssblValue] [decimal](18, 2) NULL,
	[DeferrTax] [varchar](1) NULL,
	[BaseRef] [varchar](16) NULL,
	[ItmTaxType] [varchar](2) NULL,
	[PQTReqDate] [datetime] NULL,
	[PQTReqQty] [decimal](18, 2) NULL,
	[ISDtCryImp] [varchar](3) NULL,
	[CredOrigin] [varchar](1) NULL,
	[NCMCode] [int] NULL,
	[length2] [decimal](18, 2) NULL,
	[ReturnRsn] [int] NULL,
	[StckAppDSC] [decimal](18, 2) NULL,
	[DelivrdQty] [decimal](18, 2) NULL,
	[HsnEntry] [int] NULL,
	[CESTCode] [int] NULL,
	[GTotalFC] [decimal](18, 2) NULL,
	[OriBAbsEnt] [int] NULL,
	[RetirAPCSC] [decimal](18, 2) NULL,
	[LinManClsd] [varchar](1) NULL,
	[TaxPerUnit] [decimal](18, 2) NULL,
	[Hght2Unit] [int] NULL,
	[OriBDocTyp] [int] NULL,
	[NoInvtryMv] [varchar](1) NULL,
	[Commission] [decimal](18, 2) NULL,
	[TaxDistSSC] [decimal](18, 2) NULL,
	[ExpUUID] [varchar](50) NULL,
	[U_RBI_Comprador] [varchar](30) NULL,
	[RetireAPC] [decimal](18, 2) NULL,
	[BaseQty] [decimal](18, 2) NULL,
	[FisrtBin] [varchar](228) NULL,
	[PoItmNum] [int] NULL,
	[DIOTNat] [varchar](3) NULL,
	[StgEntry] [int] NULL,
	[ShipFromCo] [varchar](50) NULL,
	[StckDstFc] [decimal](18, 2) NULL,
	[CUSplit] [varchar](1) NULL,
	[NumPerMsr2] [decimal](18, 2) NULL,
	[Project] [varchar](20) NULL,
	[NeedQty] [varchar](1) NULL,
	[PcQuantity] [decimal](18, 2) NULL,
	[UomCode] [varchar](20) NULL,
	[ISDtRgnImp] [int] NULL,
	[VatSumFrgn] [decimal](18, 2) NULL,
	[ShipDate] [datetime] NULL,
	[SubCatNum] [varchar](50) NULL,
	[RevCharge] [varchar](1) NULL,
	[DedVatSumF] [decimal](18, 2) NULL,
	[Rate] [decimal](18, 2) NULL,
	[EncryptIV] [varchar](100) NULL,
	[Width2] [decimal](18, 2) NULL,
	[ExLineNo] [varchar](10) NULL,
	[FreeChrgBP] [varchar](1) NULL,
	[GrossBase] [int] NULL,
	[CSTfCOFINS] [varchar](2) NULL,
	[OpenRtnQty] [decimal](18, 2) NULL,
	[ThirdParty] [varchar](1) NULL,
	[ConsumeFCT] [varchar](1) NULL,
	[OpenQty] [decimal](18, 2) NULL,
	[StockPrice] [decimal](18, 2) NULL,
	[StdItemId] [int] NULL,
	[TotalFrgn] [decimal](18, 2) NULL,
	[StgDesc] [varchar](100) NULL,
	[ISDistrbSC] [decimal](18, 2) NULL,
	[SerialNum] [varchar](17) NULL,
	[ExciseAmt] [decimal](21, 0) NULL,
	[IsByPrdct] [varchar](1) NULL,
	[CNJPMan] [varchar](14) NULL,
	[ActBaseLn] [int] NULL,
	[TaxAmtSrc] [varchar](1) NULL,
	[WtCalced] [varchar](1) NULL,
	[IsCstmAct] [varchar](1) NULL,
	[StckINMPr] [decimal](18, 2) NULL,
	[OpenCreQty] [decimal](18, 2) NULL,
	[PickIdNo] [int] NULL,
	[SpecPrice] [varchar](1) NULL,
	[ExtTaxSumF] [decimal](18, 2) NULL,
	[BasePrice] [varchar](1) NULL,
	[ObjType] [varchar](20) NULL,
	[U_CodLin] [varchar](10) NULL,
	[LstBINMPr] [decimal](18, 2) NULL,
	[TaxStatus] [varchar](1) NULL,
	[LegalTIMD] [varchar](250) NULL,
	[ExtTaxSumS] [decimal](18, 2) NULL,
	[TrgetEntry] [int] NULL,
	[Weight1] [decimal](18, 2) NULL,
	[Weight2] [decimal](18, 2) NULL,
	[CiOppLineN] [int] NULL,
	[InvQtyOnly] [varchar](1) NULL,
	[DstrbSumFC] [decimal](18, 2) NULL,
	[ExpOpType] [varchar](1) NULL,
	[BaseOpnQty] [decimal](18, 2) NULL,
	[Length1] [decimal](18, 2) NULL,
	[BaseType] [int] NULL,
	[OriBLinNum] [int] NULL,
	[RetireQty] [decimal](18, 2) NULL,
	[VatExLN] [int] NULL,
	[ISOrCryExp] [varchar](3) NULL,
	[StckDstSc] [decimal](18, 2) NULL,
	[CountryOrg] [varchar](3) NULL,
	[DistribSum] [decimal](18, 2) NULL,
	[VolUnit] [int] NULL,
	[Height1] [decimal](18, 2) NULL,
	[Height2] [decimal](18, 2) NULL,
	[LineVatlF] [decimal](18, 2) NULL,
	[TranType] [varchar](1) NULL,
	[PoTrgEntry] [varchar](11) NULL,
	[PoLineNum] [int] NULL,
	[AllocBinC] [varchar](11) NULL,
	[Volume] [decimal](18, 2) NULL,
	[ReleasQtty] [decimal](18, 2) NULL,
	[CtrSealQty] [decimal](18, 2) NULL,
	[Factor1] [decimal](18, 2) NULL,
	[Factor2] [decimal](18, 2) NULL,
	[Factor3] [decimal](18, 2) NULL,
	[Factor4] [decimal](18, 2) NULL,
	[BaseLine] [int] NULL,
	[StgSeqNum] [int] NULL,
	[U_DescCComer] [decimal](18, 2) NULL,
	[ImportLog] [varchar](20) NULL,
	[ISOrRgnExp] [int] NULL,
	[PriceEdit] [varchar](1) NULL,
	[FromWhsCod] [varchar](8) NULL,
	[OcrCode2] [varchar](8) NULL,
	[OcrCode3] [varchar](8) NULL,
	[OcrCode4] [varchar](8) NULL,
	[OcrCode5] [varchar](8) NULL,
	[LegalTCD] [varchar](250) NULL,
	[U_RBI_DispVentas] [decimal](18, 2) NULL,
	[ExtTaxSum] [decimal](18, 2) NULL,
	[ExtTaxRate] [decimal](18, 2) NULL,
	[OpenSumFC] [decimal](18, 2) NULL,
	[Wght1Unit] [int] NULL,
	[VatWoDpmSc] [decimal](18, 2) NULL,
	[BackOrdr] [varchar](1) NULL,
	[U_DescFide] [decimal](18, 2) NULL,
	[IsPrscGood] [varchar](1) NULL,
	[DescOW] [varchar](1) NULL,
	[Incoterms] [int] NULL,
	[CommClass] [int] NULL,
	[CEECFlag] [varchar](1) NULL,
	[ActDelDate] [datetime] NULL,
	[TransMod] [int] NULL,
	[ChgAsmBoMW] [varchar](1) NULL
)