CREATE TABLE [stg].[OrdenCompraCabecera] (
	[DocEntry] [int] NULL,
	[DocNum] [int] NULL,
	[DocType] [varchar](100) NULL,
	[CANCELED] [varchar](100) NULL,
	[Handwrtten] [varchar](100) NULL,
	[Printed] [varchar](10) NULL,
	[DocStatus] [varchar](100) NULL,
	[DocDate] [datetime] NULL,
	[DocDueDate] [datetime] NULL,
	[CardCode] [varchar](200) NULL,
	[CardName] [varchar](200) NULL,
	[CtlAccount] [varchar](100) NULL,
	[PTICode] [varchar](100) NULL,
	[Letter] [varchar](100) NULL,
	[NumAtCard] [varchar](100) NULL,
	[FolNumTo] [varchar](100) NULL,
	[JrnlMemo] [varchar](100) NULL,
	[UpdateDate] [datetime] NULL,
	[CreateDate] [datetime] NULL,
	[TransId] [varchar](100) NULL,
	[Indicator] [varchar](100) NULL,
	[U_RBI_EXTCOD] [varchar](200) NULL
)
