-----------------------------------------------------------
-- Funtion Cast Rubro
-----------------------------------------------------------
alter FUNCTION rtl.F_CastRubroName (@RubroName varchar(100))
Returns VARCHAR(200)
AS
Begin
Declare @Result VARCHAR(200)

set @Result = (UPPER(isnull(
                case
                When @RubroName = 'Mascaras' Then 'COSMETICA'
                When @RubroName = 'Mascaras WaterProof' Then 'COSMETICA'
                When @RubroName = 'Mascaras Alargadora' Then 'COSMETICA'
                When @RubroName = 'Mascara de Volumen' Then 'COSMETICA'
                When @RubroName = 'Delineador Lapiz' Then 'COSMETICA'
                When @RubroName = 'Delineador Liquido' Then 'COSMETICA'
                When @RubroName = 'Cejas' Then 'COSMETICA'
                When @RubroName = 'Sombra Mono' Then 'COSMETICA'
                When @RubroName = 'Sombra Duo' Then 'COSMETICA'
                When @RubroName = 'Sombra Trio' Then 'COSMETICA'
                When @RubroName = 'Sombra Cuarteto' Then 'COSMETICA'
                When @RubroName = 'Labial' Then 'COSMETICA'
                When @RubroName = 'Gloss' Then 'COSMETICA'
                When @RubroName = 'Brillo' Then 'COSMETICA'
                When @RubroName = 'Delineador' Then 'COSMETICA'
                When @RubroName = 'Iluminador Compacto' Then 'COSMETICA'
                When @RubroName = 'Iluminador Cremoso' Then 'COSMETICA'
                When @RubroName = 'Iluminador Líquido' Then 'COSMETICA'
                When @RubroName = 'Base Compacta' Then 'COSMETICA'
                When @RubroName = 'Base Cremosa' Then 'COSMETICA'
                When @RubroName = 'Base Liquida' Then 'COSMETICA'
                When @RubroName = 'Polvo Compacto' Then 'COSMETICA'
                When @RubroName = 'Polvo Cremoso' Then 'COSMETICA'
                When @RubroName = 'Polvo Volatil' Then 'COSMETICA'
                When @RubroName = 'Paleta' Then 'COSMETICA'
                When @RubroName = 'Rubor' Then 'COSMETICA'
                When @RubroName = 'Paleta Rubor' Then 'COSMETICA'
                When @RubroName = 'Corrector Liquido' Then 'COSMETICA'
                When @RubroName = 'Correcto Barra' Then 'COSMETICA'
                When @RubroName = 'Esmalate Color ( Var' Then 'COSMETICA'
                When @RubroName = 'Esmalte Cuidado Espe' Then 'COSMETICA'
                When @RubroName = 'KIT Uñas' Then 'COSMETICA'
                When @RubroName = 'Kit Cosmética' Then 'COSMETICA'
                When @RubroName = 'Accesorios cosmética' Then 'COSMETICA'
                When @RubroName = 'Set Cosmética' Then 'COSMETICA'
                When @RubroName = 'Hidratante' Then 'TRATAMIENTO'
                When @RubroName = 'Antiarrugas' Then 'TRATAMIENTO'
                When @RubroName = 'Exfoliante' Then 'TRATAMIENTO'
                When @RubroName = 'Reafirmante' Then 'TRATAMIENTO'
                When @RubroName = 'Cuidado Especial' Then 'TRATAMIENTO'
                When @RubroName = 'Cabello' Then 'TRATAMIENTO'
                When @RubroName = 'Busto' Then 'TRATAMIENTO'
                When @RubroName = 'Cuello y Escote' Then 'TRATAMIENTO'
                When @RubroName = 'Ojos' Then 'TRATAMIENTO'
                When @RubroName = 'Limpiadora' Then 'TRATAMIENTO'
                When @RubroName = 'Tonico' Then 'TRATAMIENTO'
                When @RubroName = 'Pieles Grasas' Then 'TRATAMIENTO'
                When @RubroName = 'Pieles Sensibles' Then 'TRATAMIENTO'
                When @RubroName = 'Solares' Then 'TRATAMIENTO'
                When @RubroName = 'Kit Cosmetica' Then 'TRATAMIENTO'
                When @RubroName = 'Shower Gel' Then 'FRAGANCIA'
                When @RubroName = 'Jabon' Then 'FRAGANCIA'
                When @RubroName = 'Deo Stick' Then 'FRAGANCIA'
                When @RubroName = 'Sales de baño' Then 'FRAGANCIA'
                When @RubroName = 'Deo Spray' Then 'FRAGANCIA'
                When @RubroName = 'Body Splash' Then 'FRAGANCIA'
                When @RubroName = 'After Shave' Then 'FRAGANCIA'
                When @RubroName = 'Deo Rollon' Then 'FRAGANCIA'
                When @RubroName = 'Kit Fragancia' Then 'FRAGANCIA'
                When @RubroName = 'Body Lotion' Then 'FRAGANCIA'
                When @RubroName = 'Set' Then 'FRAGANCIA'
                When @RubroName = 'Shampoo' Then 'FRAGANCIA'
                When @RubroName = 'Acondicionador' Then 'FRAGANCIA'
                When @RubroName = 'EDT' Then 'FRAGANCIA'
                When @RubroName = 'EDP' Then 'FRAGANCIA'
                When @RubroName = 'EDC' Then 'FRAGANCIA'
                When @RubroName = 'PLV-Miniaturas' Then 'OBSEQUIOS '
                When @RubroName = 'PLV-Muestras' Then 'OBSEQUIOS '
                When @RubroName = 'PLV-Obsequios' Then 'OBSEQUIOS '
                When @RubroName = 'PLV-Trousse' Then 'OBSEQUIOS '
                When @RubroName = 'PLV-Trousse+ miniatu' Then 'OBSEQUIOS '
                When @RubroName = 'PLV-Trousse+muestras' Then 'OBSEQUIOS '
                When @RubroName = 'PLV-Bolsos' Then 'OBSEQUIOS '
                When @RubroName = 'PLV-Blotter' Then 'REGALERIA '
                When @RubroName = 'PLV-Bolsa' Then 'REGALERIA '
                When @RubroName = 'PLV-Cajas' Then 'REGALERIA '
                When @RubroName = 'PLV-Cubos' Then 'REGALERIA '
                When @RubroName = 'PLV-Display' Then 'REGALERIA '
                When @RubroName = 'PLV-Etiqueta' Then 'REGALERIA '
                When @RubroName = 'PLV- Exhibidor' Then 'REGALERIA '
                When @RubroName = 'PLV-Folleteria' Then 'REGALERIA '
                When @RubroName = 'PLV-Forreau' Then 'REGALERIA '
                When @RubroName = 'PLV-Insumos' Then 'REGALERIA '
                When @RubroName = 'PLV-Pancarta' Then 'REGALERIA '
                When @RubroName = 'PLV- Plegadizo' Then 'REGALERIA '
                When @RubroName = 'PLV- Podium' Then 'REGALERIA '
                When @RubroName = 'PLV-Portatester' Then 'REGALERIA '
                When @RubroName = 'PLV-Prensa' Then 'REGALERIA '
                When @RubroName = 'PLV- Registro' Then 'REGALERIA '
                When @RubroName = 'PLV-Regleta' Then 'REGALERIA '
                When @RubroName = 'PLV-Sobres' Then 'REGALERIA '
                When @RubroName = 'PLV-Soporte' Then 'REGALERIA '
                When @RubroName = 'PLV-Entrenamiento' Then 'REGALERIA '
                When @RubroName = 'PLV-Vario' Then 'REGALERIA '
                When @RubroName = 'PLV-Visual' Then 'REGALERIA '
                When @RubroName = 'PLV-Probador Trat' Then 'REGALERIA '
                When @RubroName = 'PLV-Ficticios' Then 'REGALERIA '
                When @RubroName = 'PLV-Probador Cosm' Then 'REGALERIA '
                When @RubroName = 'PLV-Probador Aromas' Then 'PROBADORES'
                When @RubroName = 'PLV-Probador Frag' Then 'PROBADORES'
                When @RubroName = 'Accesorios' Then 'ACCESORIOS'
                When @RubroName = 'Gif Card' Then 'GIF CARD'
                When @RubroName = 'Insumos generales' Then 'INSUMOS'
                When @RubroName = 'Relojes' Then 'RELOJ'
                When @RubroName = 'BOD-Body Lotion' Then 'BODY'
                When @RubroName = 'BOD-Shower Gel' Then 'BODY'
                When @RubroName = 'BOD-Deo Rollon' Then 'BODY'
                When @RubroName = 'BOD-Manos' Then 'BODY'
                When @RubroName = 'BOD-Jabon' Then 'BODY'
                When @RubroName = 'BOD-Sanitizantes' Then 'BODY'
                When @RubroName = 'BOD-Deo Stick' Then 'BODY'
                When @RubroName = 'BOD-Sales de Baño' Then 'BODY'
                When @RubroName = 'BOD-Deo Spray' Then 'BODY'
                When @RubroName = 'BOD-After Shave' Then 'BODY'
                When @RubroName = 'BOD-Shampoo' Then 'BODY'
                When @RubroName = 'BOD-Acondicionador' Then 'BODY'
                When @RubroName = 'BOD-Tratamiento Capilar' Then 'BODY'
                When @RubroName = 'Insumos de Peluqueria' Then 'PELUQUERIA'
                When @RubroName = 'Capilares' Then 'CAPILAR'
                When @RubroName = 'Almohadas' Then 'TEXTIL'
                When @RubroName = 'Almohadones ' Then 'TEXTIL'
                When @RubroName = 'Ropa de baño ' Then 'TEXTIL'
                When @RubroName = 'Ropa de cama ' Then 'TEXTIL'
                When @RubroName = 'Ropa de cama de kids' Then 'TEXTIL'
                When @RubroName = 'Cocina' Then 'BAZAR'
                When @RubroName = 'Mesa' Then 'BAZAR'
                When @RubroName = 'Ropa de mesa' Then 'BAZAR'
                When @RubroName = 'Adornos ' Then 'DECORACION'
                When @RubroName = 'Decoracion de pared ' Then 'DECORACION'
                When @RubroName = 'Fragancias ' Then 'DECORACION'
                When @RubroName = 'Libreria' Then 'DECORACION'
                When @RubroName = 'Navidad ' Then 'DECORACION'
                When @RubroName = 'Plantas ' Then 'DECORACION'
                When @RubroName = 'Set aromas' Then 'DECORACION'
                When @RubroName = 'DESCRIPCION' Then ''
                else @RubroName
                end,'Sin Rubro'))
            )

RETURN @Result
End