//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASDWP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBProcess
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> FechaCarga { get; set; }
        public Nullable<System.DateTime> FechaProcesado { get; set; }
        public string NombreArchivo { get; set; }
        public string Estado { get; set; }
        public string EstadoDescripcion { get; set; }
        public string TipoProceso { get; set; }
        public string Archivo { get; set; }
        public string Periodicidad { get; set; }
    }
}
