//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASDWP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbQuery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DbQuery()
        {
            this.DbMapping = new HashSet<DbMapping>();
            this.DbSchedule = new HashSet<DbSchedule>();
        }
    
        public int Id { get; set; }
        public int TableId { get; set; }
        public Nullable<int> TableDestinoId { get; set; }
        public string Where { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DbMapping> DbMapping { get; set; }
        public virtual DbTableStg DbTableStg { get; set; }
        public virtual DbTables DbTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DbSchedule> DbSchedule { get; set; }
    }
}
