Create table rtl.FactVentasRTL
(
 id	int,
 Fecha_Contabilizacion	datetime,
 hora time,
 Numero	int,
 NumeroCompleto	varchar(255),
 Proveedor	varchar(255),
 Rubro	varchar(255),
 Marca	varchar(255),
 Segmento varchar(255),
 Direccion	varchar(255),
 Sucursal	varchar(255),
 CantidadItems	int,
 TotalDescuentoComercial	decimal(18,4),
 TotalDescuentofidelidad	decimal(18,4),
 PrecioUnitario	decimal(18,4),
 Total_CIva	decimal(18,4),
 VENTA_NETA decimal(18,4),
 CodigoArticulo	varchar(255),
 ArticuloDescripcion	varchar(255),
 Vendedor varchar(255),
 CodigoVendedor	varchar(100),
 EAN	varchar(255),
 Origen	varchar(255),
 NroTransaction varchar(255),
 CodigoTienda	int,
 ClienteCodigo	varchar(255),
 ClienteNombre	varchar(255),
 ClienteApellido varchar(255),
 ClienteZona	varchar(255),
 ClienteEmail	varchar(255),
 ClienteGenero	varchar(255)
)