CREATE TABLE [whs].[DimProductos]
(
	[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[Codigo] varchar(100),
	[Nombre] varchar(500),
	[Categoria_Id] int, 	
	[TipoProveedor_Id] int, 
	[ProveedorRetailCegid_Id] int, 
	[Cliente_Id] int,
	[CentroCosto_Id] int,
	[CtaContable_Id] int,
	[Fabricante_Id] int,
	[Genero_Id] int,
	[GrupoArt_Id] int,
	[Linea_Id] int,
	[Marca_Id] int,
	[TamanosConc_Id] int,
	[TamanoReal_Id] int,
	[TipoProducto_Id] int,
	[UnidadMedida_Id] int,
	[UnidadNegocio_Id] int,
	[CreateDate] datetime,
	[UpdateDate] datetime,
	
	FOREIGN KEY	([Categoria_Id]) REFERENCES whs.DimCategoria(Id),
	FOREIGN KEY	([TipoProveedor_Id]) REFERENCES whs.DimTipoProveedor(Id),
	FOREIGN KEY	([ProveedorRetailCegid_Id]) REFERENCES whs.DimProveedorRetailCegid(Id),
	FOREIGN KEY	([Cliente_Id]) REFERENCES whs.DimClientes(Id),
	FOREIGN KEY	([CentroCosto_Id]) REFERENCES whs.DimCentroCostos(Id),
	FOREIGN KEY	([CtaContable_Id]) REFERENCES whs.DimCuentasContables(Id),
	FOREIGN KEY	([Fabricante_Id]) REFERENCES whs.DimFabricante(Id),
	FOREIGN KEY	([Genero_Id]) REFERENCES whs.DimGenero(Id),
	FOREIGN KEY	([GrupoArt_Id]) REFERENCES whs.DimGruposArts(Id),
	FOREIGN KEY	([Linea_Id]) REFERENCES whs.Dimlineas(Id),
	FOREIGN KEY	([Marca_Id]) REFERENCES whs.DimMarcas(Id),
	FOREIGN KEY	([TamanosConc_Id]) REFERENCES whs.DimTamanosConc(Id),
	FOREIGN KEY	([TamanoReal_Id]) REFERENCES whs.DimTamanoReal(Id),
	FOREIGN KEY	([TipoProducto_Id]) REFERENCES whs.DimTiposProductos(Id),
	FOREIGN KEY	([UnidadMedida_Id]) REFERENCES whs.DimUnidadesMedida(Id),
	FOREIGN KEY	([UnidadNegocio_Id]) REFERENCES whs.DimUnidadesNegocio(Id)

)