CREATE TABLE [whs].[FactComprobantes]
(
	Id int identity(1,1) primary key,
	DocEntry int, 
	DocNum int,
	DocType varchar(10), 
	CANCELED varchar(10),
	Handwrtten varchar(10) ,
	Printed varchar(10),
	DocStatus varchar(10),
	DocDate datetime,
	DocDueDate datetime,	
	CtlAccount varchar(100),
	UpdateDate datetime,
	CreateDate datetime,
	LineNum int,
	Price decimal(18,2),
	Currency varchar(20),
	LineTotal decimal(18,2),
	OpenSum decimal(18,2),
	SlpCode int,
	AcctCode varchar(500),
	PriceBefDi decimal(18,2),
	BaseCard varchar(500),
	TotalSumSy decimal(18,2),
	OpenSumSys decimal(18,2),
	VatPrcnt decimal(18,2),
	PriceAfVAT decimal(18,2),
	VatSum decimal(18,2),
	VatSumSy decimal(18,2),
	DedVatSum decimal(18,2),
	DedVatSumS decimal(18,2),
	GrssProfit decimal(18,2),
	GrssProfSC decimal(18,2),
	VisOrder int,
	INMPrice decimal(18,2),
	TaxCode varchar(100),
	LineVat decimal(18,2),
	LineVatS decimal(18,2),
	OwnerCode varchar(500),
	StockSum decimal(18,2),
	StockSumSc decimal(18,2),
	ShipToCode varchar(500),
	ShipToDesc varchar(500),
	GTotal decimal(18,2),
	GTotalSC decimal(18,2),
	TaxOnly varchar(500),
	PTICode varchar(100), 
	Letter varchar(100),
	NumAtCard varchar(100),
	FolNumTo varchar(100) null,
	JrnlMemo varchar(100) null,
	UnidadNegocioVentaId int,
	PlanCuenta_Id int,
	Departamento_Id int,
	LugarCliente_Id int,
	PropioTercero_Id int,
	TipoProducto_Id int,
	TipoComprobante_Id int,
	GPBefDisc decimal(18,2),
	Cliente_Id int,
	Producto_Id int,
	foreign key (UnidadNegocioVentaId) references [whs].[DimUnidadesNegocioVenta](Id),
	foreign key (PlanCuenta_Id) references [whs].[DimPlanDeCuentas](Id),
	foreign key (Departamento_Id) references [whs].[DimDepartamentos](Id),
	foreign key (LugarCliente_Id) references [whs].[DimLugarCliente](Id),
	foreign key (PropioTercero_Id) references [whs].[DimPropioTercero](Id),
	foreign key (TipoProducto_Id) references [whs].[DimTiposProductos](Id),
	foreign key (TipoComprobante_Id) references [whs].[DimTipoComprobantes](Id),
	foreign key (Cliente_Id) references [whs].[DimBusinessPartner](Id),
	foreign key (Producto_Id) references [whs].[DimProductos](Id)
)
