CREATE TABLE [whs].[FactInventario]
(
	[Id] INT identity(1,1) NOT NULL PRIMARY KEY,
	TransNum int,
	TransType int,
	CreatedBy int,
	BASE_REF int,
	DocLineNum int,
	DocDate datetime,
	DocDueDate datetime,
	CardCode varchar (200),
	CardName varchar (200),
	Ref1 varchar (200),
	Ref2 varchar (200),
	Comments varchar (max),
	JrnlMemo varchar (200),
	DocTime int,
	ItemCode varchar (200),
	Dscription varchar (200),
	InQty decimal (18,4),
	OutQty decimal (18,4),
	Price decimal (18,4),
	Currency varchar (10),
	Rate decimal (18,4),
	VendorNum varchar (200),
	SerialNum varchar (200),
	Warehouse varchar (200),
	TreeType varchar (10),
	SlpCode int,
	TaxDate datetime,
	DataSource varchar (10),
	PrjCode varchar (100),
	UserSign int,
	BlockNum varchar (200),
	ImportLog varchar (200),
	UseDocPric varchar (200),
	[Location] varchar (200),
	CalcPrice decimal (18,4),
	OpenQty decimal (18,4),
	Instance int,
	LastInst int,
	RevalTotal decimal (18,4),
	BaseCurr varchar (200),
	ApplObj int,
	AppObjAbs int,
	AppObjType varchar (200),
	StockAct varchar (200),
	TrnsfrAct varchar (200),
	PriceDifAc varchar (200),
	VarianceAc varchar (200),
	ReturnAct varchar (200),
	ExcRateAct varchar (200),
	ClearAct varchar (200),
	CostAct varchar (200),
	WipAct varchar (200),
	Balance decimal (18,4),
	CreateDate  datetime,
	BaseLine int,
	TransValue decimal (18,4),
	PriceDiff decimal (18,4),
	TransSeq int,
	InvntAct varchar (200),
	RemMethod varchar (10),
	OpenValue decimal (18,4),
	SubLineNum int,
	AppObjLine int,
	Expenses decimal (18,4),
	OpenExp decimal (18,4),
	Allocation decimal (18,4),
	OpenAlloc decimal (18,4),
	ExpAlloc decimal (18,4),
	OExpAlloc decimal (18,4),
	OpenPDiff decimal (18,4),
	ExchDiff decimal (18,4),
	OpenEDiff decimal (18,4),
	NegInvAdjs decimal (18,4),
	OpenNegInv decimal (18,4),
	NegStckAct varchar (200),
	BTransVal int,
	VarVal decimal (18,4),
	BExpVal decimal (18,4),
	CogsVal decimal (18,4),
	BNegAVal decimal (18,4),
	IOffIncAcc varchar (200),
	IOffIncVal decimal (18,4),
	DOffDecAcc varchar (200),
	DOffDecVal decimal (18,4),
	DecAcc varchar (200),
	DecVal decimal (18,4),
	WipVal decimal (18,4),
	WipVarAcc varchar (200),
	WipVarVal decimal (18,4),
	IncAct varchar (200),
	IncVal decimal (18,4),
	ExpCAcc varchar (200),
	CostMethod varchar (10),
	OcrCode int,
	BaseQty int,
	PrevTrans int,
	HTransSeq int,
	OcrCode2 int,
	OcrCode3 int,
	OcrCode4 int,
	OcrCode5 int,
	StgSeqNum int,
	StgEntry int,
	StgDesc varchar (200),
	Almacen_Id int,
	Producto_Id int,
	BusinessPartner_Id int,
	foreign key (Almacen_Id) references whs.DimAlmacenes(Id),
	foreign key (Producto_Id) references whs.DimProductos(Id),
	foreign key (BusinessPartner_Id) references whs.DimBusinessPartner(Id)


	)
