CREATE VIEW [whs].[Comprobantes]
	AS 


select DISTINCT
	c.DocEntry IDS_AP, 
	c.DocDate Fecha_Contabilizacion,
	JrnlMemo,
	Trim(Replace(REPLACE(JrnlMemo,c.BaseCard,''),'-','')) Tipo_Ducumento,
	PTICode + '-' + Letter + '-' + replicate('0', 8-len(FolNumTo))+ FolNumTo numerocompleto,
	c.DocNum Numero,
	c.Indicator,
	c.DocType Documento_Tipo, 
	c.CANCELED Cacelado,
	c.Handwrtten Numeracion_Manual,
	c.Printed Impreso,
	c.DocStatus Estado,	
	c.DocDueDate Fecha_Vencimiento,		
	c.SlpCode Codigo_Empleado_Venta,
	c.BaseCard Codigo_BP_Base,
	c.TaxCode Codigo_Tributario,
	c.ShipToCode Codigo_Envio,
	c.ShipToDesc Descripcion_Envio,
	c.OwnerCode Propietario_Del_Documento,
	c.VisOrder Orden,
	c.LineNum Numero_Linea,	
	c.LineTotal Total_Filas,
	c.OpenSum Cantidad_Abierta,	
	c.Currency Moneda,
	c.PriceBefDi Precio_Unitario,	
	c.TotalSumSy Tottal_Filas_SC,
	c.OpenSumSys Importe_Abierto_SC,

	case 
		when c.TaxCode = 'IVA_EXEv' then 0 
		else c.VatPrcnt 
	end Tasa_Impositiva,

	case 
		when c.TaxCode = 'IVA_EXEv' then 0 
		else c.Tasa_Impositiva_porc
	end Tasa_ImpositivaPor,

	c.PriceAfVAT Precio_Bruto_Despues_Descuento,

	case 
	when JrnlMemo like 'A/R Credit Memos%' and OpenInvQty < 0 and c.VatSum > 0 then c.VatSum *-1
	else c.VatSum
	end  Impuesto_Total ,

	c.VatSumSy Impuesto_Total_SC,
	c.DedVatSum Monto_Impuesto_Deducible,
	c.DedVatSumS Monto_Impuesto_Deducible_SC ,
	c.GrssProfit Beneficio_Bruto,
	c.GrssProfSC Beneficio_Bruto_SC,	
	c.INMPrice Precio_Venta_Articulo,	
	c.LineVat Importe_Neto_Impuestos,
	c.LineVatS Importe_Neto_Impuestos_SC,	
	c.StockSum Suma_Acciones,
	c.StockSumSc Suma_Acciones_SC,	
	c.GTotal Total_Bruto,
	c.GTotalSC Total_Bruto_SC,
	c.TaxOnly Solo_Impuestos,

	case 
	when JrnlMemo like 'A/R Credit Memos%' and OpenInvQty < 0 and c.Price < 0 then c.Price *-1
	else c.Price
	end	 Precio_Despues_Descuento,

	c.GPBefDisc,	
	c.UnidadNegocioVentaId,
	c.PlanCuenta_Id,
	c.Departamento_Id,
	c.LugarCliente_Id,
	c.PropioTercero_Id,
	c.TipoProducto_Id,
	c.TipoComprobante_Id,
	c.Producto_Id,
	c.Cliente_Id,
	c.TransId,
	c.UpdateDate,
	c.CreateDate,

	c.WtLiable, 
	c.GrssProfFC,
	c.LicTradNum,
	c.FreeTxt,
	c.NatOfTrans,
	c.PostTax,
	c.LstByDsSum,
	c.MYFtype,
	c.PartRetire,
	c.U_RBI_CantOriOc,
	c.LocCode,
	c.StckAppSc,
	c.BlockNum,
	c.VatExEntry ,
	c.StckAppDFC,
	c.SacEntry ,
	c.CFOPCode,
	c.Quantity,
	c.OrderedQty,
	c.[Address],
	c.PrntLnNum ,
	c.RG23APart1,
	c.DstrbSumSC,
	c.EnSetCost ,
	c.LineVendor ,
	c.Wght2Unit,
	c.RetirAPCFC,
	c.BaseAtCard,
	c.DiscPrcnt,
	c.ReturnAct ,
	c.LegalTTCA,
	c.ShipFromDe,
	c.Shortages,
	c.TaxDistSFC,
	c.PackQty,
	c.EquVatPer,
	c.DistribIS,
	c.StckAppFc,
	c.LogInstanc ,
	c.LinePoPrss,
	c.EquVatSumF,
	c.U_CodComer,
	c.ActBaseEnt ,
	c.ExpType,
	c.PoTrgNum,
	c.AgrLnNum,
	c.NumPerMsr,
	c.LegalTW,
	c.LineStatus,
	c.NVECode,
	c.GrossBuyPr,
	c.EquVatSumS,
	c.StckSumApp,
	c.OrigItem,
	c.BaseDocNum,
	c.RG23APart2,
	c.PcDocType,
	c.AgrNo,
	c.Dscription,
	c.CSTfIPI,
	c.ItemType,
	c.FinncPriod,
	c.DefBreak,
	c.LnExcised,
	c.TargetType,
	c.StckAppD,
	c.StockSumFc,
	c.OcrCode,
	c.PoNum,
	c.Len1Unit,
	c.LegalText,
	c.Surpluses,
	c.SWW,
	c.LstByDsSc,
	c.LineType,
	c.GPTtlBasPr,
	c.TaxDistSum,
	c.DropShip,
	c.QtyToShip,
	c.TaxRelev,
	c.TaxType,
	c.VatWoDpm,
	c.ToStock,
	c.TotInclTax,
	c.InvntSttus,
	c.TreeType,
	c.TrnsCode,
	c.DetailsOW,
	c.U_CodFide,
	isnull(c.U_DesLin,0) U_DesLin,
	c.LstByDsFc,
	c.U_RBI_CantConf,
	c.PickOty,
	c.RG23CPart1,
	c.RG23CPart2,
	c.ISDistrb,
	c.UnencReasn,
	c.UomCode2,
	c.InvQty,
	c.UomEntry,
	c.BaseEntry,
	c.DistribExp,
	c.UomEntry2,
	c.Usage,
	c.UseBaseUn,
	c.VatAppld,
	c.VatAppldSC,
	c.VatGroup,
	c.Excisable,
	c.VatGrpSrc,
	c.CSTCode,
	c.ToDiff,
	c.UpdInvntry,
	c.ActBaseNum,
	c.VatWoDpmFc,
	c.StckDstSum,
	c.VendorNum,
	c.Wdth1Unit,
	c.Wdth2Unit,
	c.ISDistrbFC,
	c.Len2Unit,
	c.RetCost,
	c.WhsCode,
	c.Flags,
	c.UFFiscBene,
	c.Width1,
	c.IsAqcuistn ,
	c.Hght1Unit ,
	c.isSrvCall ,
	c.PickStatus ,
	c.unitMsr ,
	c.IndEscala ,
	c.EquVatSum,
	c.VatDscntPr,
	c.OpenInvQty,
	c.CSTfPIS ,
	c.unitMsr2 ,
	c.CodeBars ,
	c.StockValue,
	c.VatAppldFC,
	c.AssblValue,
	c.DeferrTax ,
	c.BaseRef ,
	c.ItmTaxType ,
	c.PQTReqDate ,
	c.PQTReqQty,
	c.ISDtCryImp ,
	c.CredOrigin ,
	c.NCMCode ,
	c.length2,
	c.ReturnRsn ,
	c.StckAppDSC,
	c.DelivrdQty,
	c.HsnEntry ,
	c.CESTCode ,
	c.GTotalFC,
	c.OriBAbsEnt ,
	c.RetirAPCSC,
	c.LinManClsd ,
	c.TaxPerUnit,
	c.Hght2Unit ,
	c.OriBDocTyp ,
	c.NoInvtryMv ,
	c.Commission,
	c.TaxDistSSC,
	c.ExpUUID ,
	c.U_RBI_Comprador ,
	c.RetireAPC,
	c.BaseQty,
	c.FisrtBin ,
	c.PoItmNum ,
	c.DIOTNat ,
	c.StgEntry ,
	c.ShipFromCo ,
	c.StckDstFc,
	c.CUSplit ,
	c.NumPerMsr2,
	c.Project ,
	c.NeedQty ,
	c.UomCode ,
	c.ISDtRgnImp ,
	c.VatSumFrgn,
	c.ShipDate ,
	c.SubCatNum ,
	c.RevCharge ,
	c.DedVatSumF,
	c.Rate,
	c.EncryptIV ,
	c.Width2,
	c.ExLineNo ,
	c.FreeChrgBP ,
	c.GrossBase ,
	c.CSTfCOFINS ,
	c.OpenRtnQty,
	c.ThirdParty ,
	c.ConsumeFCT ,
	c.OpenQty,
	c.StockPrice,
	c.StdItemId ,
	c.TotalFrgn,
	c.StgDesc ,
	c.ISDistrbSC,
	c.SerialNum ,
	c.ExciseAmt,
	c.IsByPrdct ,
	c.CNJPMan ,
	c.ActBaseLn ,
	c.TaxAmtSrc ,
	c.WtCalced ,
	c.IsCstmAct ,
	c.StckINMPr,
	c.OpenCreQty,
	c.PickIdNo ,
	c.SpecPrice ,
	c.ExtTaxSumF,
	c.BasePrice ,
	c.ObjType ,
	c.U_CodLin ,
	c.LstBINMPr,
	c.TaxStatus ,
	c.LegalTIMD ,
	c.ExtTaxSumS,
	c.TrgetEntry ,
	c.Weight1,
	c.Weight2,
	c.CiOppLineN ,
	c.InvQtyOnly ,
	c.DstrbSumFC,
	c.ExpOpType ,
	c.BaseOpnQty,
	c.Length1,
	c.BaseType ,
	c.OriBLinNum ,
	c.RetireQty,
	c.VatExLN ,
	c.ISOrCryExp ,
	c.StckDstSc,
	c.CountryOrg ,
	c.DistribSum,
	c.VolUnit ,
	c.Height1,
	c.Height2,
	c.LineVatlF,
	c.TranType ,
	c.PoTrgEntry,
	c.PoLineNum ,
	c.AllocBinC,
	c.Volume,
	c.ReleasQtty,
	c.CtrSealQty,
	c.Factor1,
	c.Factor2,
	c.Factor3,
	c.Factor4,
	c.BaseLine ,
	c.StgSeqNum ,
	isnull(c.U_DescCComer,0) U_DescCComer,
	c.ImportLog ,
	c.ISOrRgnExp ,
	c.PriceEdit ,
	c.FromWhsCod,
	c.OcrCode2 ,
	c.OcrCode3 ,
	c.OcrCode4 ,
	c.OcrCode5 ,
	c.LegalTCD ,
	c.U_RBI_DispVentas,
	c.ExtTaxSum,
	c.ExtTaxRate,
	c.OpenSumFC,
	c.Wght1Unit ,
	c.VatWoDpmSc,
	c.BackOrdr ,
	isnull(c.U_DescFide,0) U_DescFide,
	c.IsPrscGood ,
	c.DescOW ,
	c.Incoterms ,
	c.CommClass ,
	c.CEECFlag ,
	c.ActDelDate ,
	c.TransMod ,
	c.ChgAsmBoMW,
	AcctCode,
	CogsAcct,
	CtlAccount,
	p.Codigo ItemCode,
	case 
		when JrnlMemo like '%Facturas clientes%' or JrnlMemo like '%Facturas de clientes%'   then 'MAYORISTA'
		when JrnlMemo like '%A/R Invoices%' AND OcrCode3 = 30003  then 'MAYORISTA'
		when JrnlMemo like '%/R Invoices%' AND OcrCode3 <> 30003  then 'RETAIL'
		when JrnlMemo like '%/R Credit Memos%' AND OcrCode3 = 30003  then 'MAYORISTA'
		when JrnlMemo like '%A/R Credit Memos%' AND OcrCode3 <> 30003  then 'RETAIL'
		when JrnlMemo like '%Notas de crédito clientes%'  then 'MAYORISTA'
		else NULL
	end Direccion,
	Origen,


case 
	when c.GTotal = 0 or c.Tasa_Impositiva_porc = 0  then 0
	else
		convert(decimal(18,6), c.GTotal/c.Tasa_Impositiva_porc) 
end Total_Bruto_SIN_IVA,


convert( decimal(18,4), 
				case  when Tasa_Impositiva_porc > 0 then c.GTotal / Tasa_Impositiva_porc
					else 0
				end)  VENTA_NETA,

case 
	when JrnlMemo like '%A/R Invoices%' or JrnlMemo like '%A/R Credit Memos%' then (U_DescCComer + U_Deslin + U_DescFide ) / Tasa_Impositiva_porc
	when JrnlMemo like '%Facturas clientes%' or JrnlMemo like '%Notas de crédito clientes%'or JrnlMemo like '%Notas de credito clientes%' then (c.PriceBefDi - c.Price) * InvQty 
	else 0
end Dto_Total_SIN_IVA,

'SAP' Escenario,
[U_RBI_EXTCOD]
	
from whs.FactComprobantes c with(nolock) 
LEFT JOIN WHS.DimProductos P ON P.id = c.Producto_Id
where CANCELED = 'N'