CREATE VIEW [whs].[Comprobantes]
	AS 


select 
	c.DocEntry IDS_AP, 
	c.DocDate Fecha_Contabilizacion,
	JrnlMemo,
	PTICode + '-' + Letter + '-' + replicate('0', 8-len(FolNumTo))+ FolNumTo numerocompleto,
	c.DocNum Numero,
	c.DocType Documento_Tipo, 
	c.CANCELED Cacelado,
	c.Handwrtten Numeracion_Manual,
	c.Printed Impreso,
	c.DocStatus Estado,	
	c.DocDueDate Fecha_Vencimiento,		
	c.SlpCode Codigo_Empleado_Venta,
	c.BaseCard Codigo_BP_Base,
	c.TaxCode Codigo_Tributario,
	c.ShipToCode Codigo_Envio,
	c.ShipToDesc Descripcion_Envio,
	c.OwnerCode Propietario_Del_Documento,
	c.VisOrder Orden,
	c.LineNum Numero_Linea,	
	c.LineTotal Total_Filas,
	c.OpenSum Cantidad_Abierta,	
	c.Currency Moneda,
	c.PriceBefDi Precio_Unitario,	
	c.TotalSumSy Tottal_Filas_SC,
	c.OpenSumSys Importe_Abierto_SC,
	c.VatPrcnt Tasa_Impositiva,
	c.PriceAfVAT Precio_Bruto_Despues_Descuento,
	c.VatSum Impuesto_Total ,
	c.VatSumSy Impuesto_Total_SC,
	c.DedVatSum Monto_Impuesto_Deducible,
	c.DedVatSumS Monto_Impuesto_Deducible_SC ,
	c.GrssProfit Beneficio_Bruto,
	c.GrssProfSC Beneficio_Bruto_SC,	
	c.INMPrice Precio_Venta_Articulo,	
	c.LineVat Importe_Neto_Impuestos,
	c.LineVatS Importe_Neto_Impuestos_SC,	
	c.StockSum Suma_Acciones,
	c.StockSumSc Suma_Acciones_SC,	
	c.GTotal Total_Bruto,
	c.GTotalSC Total_Bruto_SC,
	c.TaxOnly Solo_Impuestos,
	c.Price Precio_Despues_Descuento,
	c.GPBefDisc,	
	c.UnidadNegocioVentaId,
	c.PlanCuenta_Id,
	c.Departamento_Id,
	c.LugarCliente_Id,
	c.PropioTercero_Id,
	c.TipoProducto_Id,
	c.TipoComprobante_Id,
	c.Producto_Id,
	c.Cliente_Id,
	c.UpdateDate,
	c.CreateDate
	
from whs.FactComprobantes c with(nolock)
