//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASDWP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuSecurity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MenuSecurity()
        {
            this.ItemMenuSecurity = new HashSet<ItemMenuSecurity>();
        }
    
        public int Id { get; set; }
        public string User_Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<bool> IsActivo { get; set; }
        public Nullable<int> Orden { get; set; }
        public string OcrCode3 { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemMenuSecurity> ItemMenuSecurity { get; set; }
    }
}
