//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASDWP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RabbitMessageMapping
    {
        public int Id { get; set; }
        public string ColumnName { get; set; }
        public string JsonAttribute { get; set; }
        public Nullable<int> RabbitQueueId { get; set; }
    }
}
