//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASDWP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RabbitQueue
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string ExchangeName { get; set; }
        public string QueueName { get; set; }
        public string RoutingKey { get; set; }
        public Nullable<System.DateTime> UltimaEjecucion { get; set; }
        public Nullable<System.DateTime> ProximaEjecucion { get; set; }
        public string Estado { get; set; }
        public string Origen { get; set; }
        public string tipo { get; set; }
        public string TableDestinoDw { get; set; }
    }
}
