//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASDWP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RabbitMenssage
    {
        public int Id { get; set; }
        public string Msg { get; set; }
        public string Estado { get; set; }
        public Nullable<int> RabbitQueue_Id { get; set; }
        public Nullable<System.DateTime> ImportDate { get; set; }
        public Nullable<System.Guid> ProcessId { get; set; }
        public string JsonTransactionID { get; set; }
    }
}
